language: php

php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer install --prefer-source --dev
  - php app/console assetic:dump --env=prod --no-debug

script:
  - ./bin/phpunit
  - ./bin/behat
  - ./bin/phpspec run
