- hosts: application
  sudo: yes
  vars_files:
    - ../../../app/config/parameters.yml
  tasks:
    - name: Install elasticsearch repo key
      shell: "wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -"
    - name: Add repo
      apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.2/debian stable main' state=present
    - name: Install elasticsearch packages
      action: apt name="{{ item }}"
      with_items:
        - elasticsearch      
    - name: Start the elasticsearch service
      action: service name=elasticsearch state=started
  handlers:
    - name: RestartElasticSearch
      service: name=elasticsearch state=restarted
