- hosts: db
  sudo: yes
  vars_files:
    - ../../../app/config/parameters.yml
  tasks:
    - name: Install MySQL
      action: apt name="{{ item }}"
      with_items:
        - python-mysqldb
        - mysql-server
    - name: Start the MySQL service
      action: service name=mysql state=started
    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ parameters.database_password }} priv=*.*:ALL,GRANT
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - "%"
        - localhost

    - name: copy .my.cnf file with root password credentials
      template: src=mysql/root.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
      notify:
        - RestartMysql

    - name: set mysql my.cnf
      template: src=mysql/my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0600
      notify:
        - RestartMysql

    - name: delete anonymous MySQL server user for $server_hostname
      action: mysql_user user="" host="$server_hostname" state="absent"

    - name: delete anonymous MySQL server user for localhost
      action: mysql_user user="" state="absent"

    - name: remove the MySQL test database
      action: mysql_db db=test state=absent
      
    - name: add dev MySQL  database
      action: mysql_db db={{ parameters.database_name }} state=present
      
  handlers:
    - name: RestartMysql
      service: name=mysql state=restarted
