parameters:
#    null_dev_user.example.class: NullDev\UserBundle\Example

services:
#    null_dev_user.example:
#        class: %null_dev_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
