null_dev_base_homepage:
    pattern:  /
    defaults: { _controller: NullDevBaseBundle:MainPage:index }

null_dev_base_impressum:
    pattern:  /impressum
    defaults: { _controller: NullDevBaseBundle:MainPage:impressum }

