parameters:
#    null_dev_base.example.class: NullDev\BaseBundle\Example

services:
#    null_dev_base.example:
#        class: %null_dev_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
